#!/usr/bin/env bash
#
# Script to load/unload all Surface System Aggregator modules
#

unload() {
    cmd=${1}

    if [ $(systemctl list-unit-files "surface-dtx-daemon.service" | wc -l) -gt 3 ]
    then
        systemctl stop surface-dtx-daemon.service
    fi

    systemctl stop upower.service
    modprobe -r battery
    modprobe -r ac

    ${cmd} surface_perfmode
    ${cmd} surface_kbd
    ${cmd} surface_hid
    ${cmd} surface_hid_core
    ${cmd} surface_dtx
    ${cmd} surface_battery
    ${cmd} surface_charger
    ${cmd} surface_acpi_notify
    ${cmd} surface_aggregator_registry
    ${cmd} surface_aggregator_cdev
    ${cmd} surface_aggregator
}

load() {
    cmd=${1}
    ext=${2}
    client_pfx=${3}

    ${cmd} surface_aggregator"${ext}"
    ${cmd} "${client_pfx}"surface_aggregator_cdev"${ext}"
    ${cmd} "${client_pfx}"surface_acpi_notify"${ext}"
    ${cmd} "${client_pfx}"surface_battery"${ext}"
    ${cmd} "${client_pfx}"surface_charger"${ext}"
    ${cmd} "${client_pfx}"surface_dtx"${ext}"
    ${cmd} "${client_pfx}"surface_hid_core"${ext}"
    ${cmd} "${client_pfx}"surface_hid"${ext}"
    ${cmd} "${client_pfx}"surface_kbd"${ext}"
    ${cmd} "${client_pfx}"surface_perfmode"${ext}"
    ${cmd} "${client_pfx}"surface_aggregator_registry"${ext}"

    if [ $(systemctl list-unit-files "surface-dtx-daemon.service" | wc -l) -gt 3 ]
    then
        systemctl start surface-dtx-daemon.service
    fi

    modprobe battery
    modprobe ac
    systemctl restart upower.service
}

help() {
    echo "usage:"
    echo "  ${0}            run 'modprobe' on ssam modules"
    echo "  ${0} -r         run 'modprobe -r' on ssam modules"
    echo "  ${0} insmod     run 'insmod' on ssam .ko modules"
    echo "  ${0} rmmod      run 'rmmod' on ssam .ko modules"
}

case ${1} in
    insmod)
        load "insmod" ".ko" "clients/"
        ;;

    rmmod)
        unload "rmmod"
        ;;

    "-r")
        unload "modprobe -r"
        ;;

    "")
        load "modprobe"
        ;;

    *)
        help
        ;;
esac
