# SPDX-License-Identifier: GPL-2.0+
# Copyright (C) 2019-2021 Maximilian Luz <luzmaximilian@gmail.com>

obj-m += surface_acpi_notify.o
obj-m += surface_aggregator_cdev.o
obj-m += surface_aggregator_registry.o
obj-m += surface_battery.o
obj-m += surface_charger.o
obj-m += surface_dtx.o
obj-m += surface_hid_core.o
obj-m += surface_hid.o
obj-m += surface_kbd.o
obj-m += surface_perfmode.o

#ccflags-y += -DDEBUG
ccflags-y += -Wall -Wextra
ccflags-y += -Wno-unused-parameter -Wno-missing-field-initializers
ccflags-y += -Wmaybe-uninitialized -Wuninitialized

ccflags-y += -DCONFIG_SURFACE_AGGREGATOR_BUS=y

# switch to handle support for both patched and non-patched kernels
ccflags-$(__KERNEL_HAS_SSAM_MODALIAS_SUPPORT__) += -D__KERNEL_HAS_SSAM_MODALIAS_SUPPORT__=1
